game.resources = [
	// Graphics: {name: "example", type:"image", src: "data/img/example.png"},
	{name: "eggy", type:"image", src: "data/img/sprite/eggy.png"},
	// area01
    {name: "refridge_level_background", type:"image", src: "data/img/backgrounds/refridge_level_background.png"},
	{name: "carton", type:"image", src: "data/img/sprite/area01/carton.png"},
	{name: "refridge_dark", type:"image", src: "data/img/sprite/area01/refridge_dark.png"},
	{name: "door2", type:"image", src: "data/img/sprite/area01/door2.png"},
	{name: "sausage_rope", type:"image", src: "data/img/sprite/area01/sausage_rope.png"},
	{name: "sausage_se", type:"image", src: "data/img/sprite/area01/sausage_se.png"},
	{name: "chicken_leg", type:"image", src: "data/img/sprite/area01/chicken_leg.png"},
	{name: "cheese", type:"image", src: "data/img/sprite/area01/cheese.png"},
	{name: "icicle", type:"image", src: "data/img/sprite/area01/icicle.png"},
	{name: "snowflakes", type:"image", src: "data/img/sprite/area01/snowflake.png"},
    {name: "icecream_pouring", type:"image", src: "data/img/sprite/area01/icecream_pouring.png"},
    {name: "fridge_obj4", type:"image", src: "data/img/sprite/area01/fridge_obj4.png"},
    {name: "breakingPlatform", type:"image", src: "data/img/sprite/area01/refridge_obj1.png"},
    //area02
    {name: "shelf_level_background", type:"image", src: "data/img/backgrounds/shelf_level_background.png"},
    {name: "books", type:"image", src: "data/img/sprite/area02/books.png"},
	{name: "applecider", type:"image", src: "data/img/sprite/area02/applecider.png"},
	{name: "pouringcider", type:"image", src: "data/img/sprite/area02/pouringcider.png"},
	{name: "mallet_movement", type:"image", src: "data/img/sprite/area02/mallet_movement.png"},
	{name: "paper_towel", type:"image", src: "data/img/sprite/area02/paper_towel.png"},
	{name: "shelf", type:"image", src: "data/img/sprite/area02/shelf.png"},
	{name: "break_pipe", type:"image", src: "data/img/sprite/area02/break_pipe.png"},
	//area03
	{name: "level_3_background", type:"image", src: "data/img/backgrounds/level_3_background.png"},
	{name: "level_3_transparent", type:"image", src: "data/img/backgrounds/level_3_transparent.png"},
    {name: "pipe", type:"image", src: "data/img/sprite/area03/pipe.png"},
	{name: "button1", type:"image", src: "data/img/sprite/area03/button1.png"},
	{name: "water_animation2", type:"image", src: "data/img/sprite/area03/water_animation2.png"},
	{name: "water_animation3", type:"image", src: "data/img/sprite/area03/water_animation3.png"},
	{name: "water_switch", type:"image", src: "data/img/sprite/area03/water_switch.png"},
	{name: "tank_a", type:"image", src: "data/img/sprite/area03/tank_a.png"},
	{name: "tank_b", type:"image", src: "data/img/sprite/area03/tank_b.png"},
	//area04
	{name: "level4", type:"image", src: "data/img/sprite/area04/level4.png"},
	{name: "sponge", type:"image", src: "data/img/sprite/area04/sponge.png"},
	{name: "sinkLid", type:"image", src: "data/img/sprite/area04/sinkLid.png"},
	{name: "sinkhole", type:"image", src: "data/img/sprite/area04/sinkhole.png"},
	{name: "flame_sprite", type:"image", src: "data/img/sprite/area04/flame_sprite.png"},
	{name: "pan", type:"image", src: "data/img/sprite/area04/pan.png"},
	//debug
	{name: "blank", type:"image", src: "data/img/sprite/debug/blank.png"},
	//{name: "onoffpallet", type:"image", src: "data/img/sprite/debug/onoffpallet.png"},
	//{name: "MultiStateEntityPallet", type:"image", src: "data/img/sprite/debug/MultiStateEntityPallet.png"},
	//{name: "switch", type:"image", src: "data/img/sprite/debug/switch.png"},
    
    // GUI images
	{name: "main_screen", type:"image", src: "data/img/backgrounds/main_screen.png"},
    {name: "pauseButton",   	  type:"image", src: "data/img/gui/pauseButton.png"},
    {name: "pause_menu",   	  type:"image", src: "data/img/gui/pause_menu.png"},
    {name: "restartButton",   	  type:"image", src: "data/img/gui/restartButton.png"},
    {name: "backButton",   	  type:"image", src: "data/img/gui/backButton.png"},
    {name: "menuButton",   	  type:"image", src: "data/img/gui/menuButton.png"},
    {name: "levelButton",   	  type:"image", src: "data/img/gui/levelButton.png"},
    {name: "instructionButton",   	  type:"image", src: "data/img/gui/instructionButton.png"},
    {name: "chooseLevelBG",   	  type:"image", src: "data/img/gui/chooseLevel.png"},
    {name: "chooseLevel1",   	  type:"image", src: "data/img/gui/chooseLevel1.png"},
    {name: "chooseLevel2",   	  type:"image", src: "data/img/gui/chooseLevel2.png"},
    {name: "chooseLevel3",   	  type:"image", src: "data/img/gui/chooseLevel3.png"},
    {name: "chooseLevel4",   	  type:"image", src: "data/img/gui/chooseLevel4.png"},
    {name: "clickEverywhere",   	  type:"image", src: "data/img/gui/clickEverywhere.png"},
    
    // Game font
    {name: "32x32_font",          type:"image", src: "data/img/font/32x32_font.png"},
	
	// Maps: {name: "example01", type: "tmx", src: "data/map/example01.tmx"},
 	{name: "main_menu", type:"tmx", src:"data/map/main_menu.tmx"},
 	{name: "area01", type:"tmx", src:"data/map/area01.tmx"},
 	{name: "area02", type:"tmx", src:"data/map/area02.tmx"},
 	{name: "area03", type:"tmx", src:"data/map/area03.tmx"},
 	{name: "area04", type:"tmx", src:"data/map/area04.tmx"},
 	
	// Background music: {name: "example_bgm", type: "audio", src: "data/bgm/", channel : 1},
    {name: "melody", type: "audio", src: "data/bgm/", channel : 1},
    {name: "area01", type: "audio", src: "data/bgm/", channel : 1},
    //{name: "pipesthemeMoreEcho", type: "audio", src: "data/bgm/", channel : 1},
	{name: "area03", type: "audio", src: "data/bgm/", channel : 1},
	{name: "area02", type: "audio", src: "data/bgm/", channel : 1},
	{name: "area04", type: "audio", src: "data/bgm/", channel : 1},
    
	// Sound effects: {name: "example_sfx", type: "audio", src: "data/sfx/", channel : 2}
    {name: "click", type: "audio", src: "data/sfx/", channel:1},
    {name: "woosh", type: "audio", src: "data/sfx/", channel:2},
    {name: "crack", type: "audio", src: "data/sfx/", channel:1},
    {name: "ice_break", type: "audio", src: "data/sfx/", channel:1},
    {name: "squelch", type: "audio", src: "data/sfx/", channel:1},
    {name: "clickeverywhere", type: "audio", src: "data/sfx/", channel:1},
    {name: "thud", type: "audio", src: "data/sfx/", channel:1},
    {name: "fridgeopen", type: "audio", src: "data/sfx/", channel:1},
    {name: "opencork", type: "audio", src: "data/sfx/", channel:1},
    {name: "cheesefall", type: "audio", src: "data/sfx/", channel:1},
    {name: "meatfalling", type: "audio", src: "data/sfx/", channel:1},
    {name: "booksfall2", type: "audio", src: "data/sfx/", channel:1},
    {name: "clink3", type: "audio", src: "data/sfx/", channel:1},
    {name: "boing", type: "audio", src: "data/sfx/", channel:1},
    {name: "hulksmash", type: "audio", src: "data/sfx/", channel:1},
    {name: "toiletroll", type: "audio", src: "data/sfx/", channel:1},
    {name: "watersplash", type: "audio", src: "data/sfx/", channel:1},
    {name: "waterfilling", type: "audio", src: "data/sfx/", channel:1},
    {name: "window_squeak", type: "audio", src: "data/sfx/", channel:1},
    {name: "onstove", type: "audio", src: "data/sfx/", channel:1},
    {name: "clunk", type: "audio", src: "data/sfx/", channel:1},
    {name: "correct", type: "audio", src: "data/sfx/", channel:1}
    
    //I see yu Brian 
    // Atlases {name: "example_tps", type: "tps", src: "data/img/example_tps.json"}
];
